version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 038462778050.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t nambath-api .
      - docker tag nambath-api:latest 038462778050.dkr.ecr.us-east-1.amazonaws.com/nambath-api:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 038462778050.dkr.ecr.us-east-1.amazonaws.com/nambath-api:latest
      - echo Writing image definitions...
      - printf '[{"name":"nambath-api","imageUri":"038462778050.dkr.ecr.us-east-1.amazonaws.com/nambath-api:latest"}]' > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
